# Generated by Django 4.2.1 on 2023-05-21 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('Apogee', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Justifiee', models.BooleanField(default=False)),
                ('Justification', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Niveau', models.CharField(max_length=100)),
                ('Delegue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.etudiant')),
                ('Filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Ordre', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.utilisateur')),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.module')),
                ('Promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Contenu', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Seen', models.BooleanField(default=False)),
                ('Utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='Promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.promotion'),
        ),
        migrations.AddField(
            model_name='module',
            name='Responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.utilisateur'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='Responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.utilisateur'),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.etudiant')),
                ('Justification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.justification')),
                ('Seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.seance')),
            ],
        ),
    ]
