# Generated by Django 4.2.1 on 2023-05-21 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_seance_ordre_alter_seance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='Justification',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.justification'),
        ),
    ]
