# Generated by Django 4.2.1 on 2023-05-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_absence_justification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='Promotion',
        ),
        migrations.AddField(
            model_name='module',
            name='Promotion',
            field=models.ManyToManyField(to='dashboard.promotion'),
        ),
    ]
