# Generated by Django 3.2.12 on 2023-06-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_absence_id_alter_absence_justification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='Niveau',
            field=models.CharField(choices=[('1A', '1ère année'), ('2A', '2ème année'), ('3A', '3ème année'), ('4A', '4ème année'), ('5A', '5ème année')], max_length=100),
        ),
    ]
