# Generated by Django 3.2.12 on 2023-06-04 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_promotion_niveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeanceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.promotion')),
            ],
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='Promotion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.promotion'),
        ),
        migrations.CreateModel(
            name='SeanceTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=100)),
                ('enseignant', models.CharField(max_length=100)),
                ('type_seance', models.CharField(max_length=100)),
                ('seance_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.seancetemplate')),
            ],
        ),
    ]
