# Generated by Django 3.2.12 on 2023-06-05 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20230604_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seancetemplateitem',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.utilisateur'),
        ),
        migrations.AlterField(
            model_name='seancetemplateitem',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.module'),
        ),
        migrations.AlterField(
            model_name='seancetemplateitem',
            name='session',
            field=models.CharField(choices=[('8h30 - 10h30', '8h30 - 10h30'), ('10h45 - 12h45', '10h45 - 12h45'), ('14h30 - 16h30', '14h30 - 16h30'), ('16h45 - 18h45', '16h45 - 18h45')], max_length=100),
        ),
        migrations.AlterField(
            model_name='seancetemplateitem',
            name='type_seance',
            field=models.CharField(choices=[('Cours', 'Cours'), ('TD', 'TD'), ('TP', 'TP')], max_length=100),
        ),
    ]
